version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ozon
    ports:
      - 5432:5432
    networks:
      - my-network
  url-shortener:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
        DB_DSN: "host=db port=5432 user=postgres password=password dbname=ozon sslmode=disable timezone=UTC connect_timeout=5"
    ports:
        - 8080:8080
    depends_on:
        - db
    networks:
        - my-network


networks:
  my-network:
